# webc appveyor configuration for Windows (x64) and Linux (x64 + ARM)

# Common configuration
image: 
- Visual Studio 2017
- Ubuntu

platform: x64

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

version: 0.1.0.{build}

stack: go 1.11

install:
  # Windows
  - cmd: set PATH=%GOPATH%\bin;%PATH%

  # Linux
  - sh: export GOPATH=/usr/go
  - sh: export PATH=$GOPATH/bin:$PATH
  - sh: sudo chmod -R a+rwx $GOPATH

build_script:
  ############################################################################
  # Windows build and zip
  - cmd: go build -ldflags="-X 'main.applicationBuildTime=%DATE% %TIME%' -X main.applicationVersion=%APPVEYOR_BUILD_VERSION% -X main.applicationGitHash=%APPVEYOR_REPO_COMMIT%" github.com/midstar/webc
  - cmd: 7z a webc_windows_x64.zip webc.exe

  ############################################################################
  # Linux PC/x64 build and zip
  - sh: go build -ldflags="-X 'main.applicationBuildTime=$DATETIME' -X main.applicationVersion=$APPVEYOR_BUILD_VERSION -X main.applicationGitHash=$APPVEYOR_REPO_COMMIT" github.com/midstar/webc
  - sh: tar -zcvf webc_linux_x64.tar.gz  webc

  ############################################################################
  # Linux ARM (cross compile from linux x64)
  - sh: rm webc
  - sh: export GOOS=linux 
  - sh: export GOARCH=arm
  - sh: export GOARM=5
  - sh: go build -ldflags="-X 'main.applicationBuildTime=$DATETIME' -X main.applicationVersion=$APPVEYOR_BUILD_VERSION -X main.applicationGitHash=$APPVEYOR_REPO_COMMIT" github.com/midstar/webc
  - sh: tar -zcvf webc_linux_arm.tar.gz  webc

# Deploy to GitHub (only on master AND on tags)
deploy:
  release: webc-v$(APPVEYOR_BUILD_VERSION)
  description: ''
  provider: GitHub
  auth_token:
    secure: C6VrW1yhX0pNCEarV0anjNU8gcM0tKbMGf+7yhuh8rLe+HnCzlzLu9Uq7EWMtYHG
  draft: false
  prerelease: false
  on:
    branch: master

for:
  
# Special configurations for Windows
-
  matrix:
    only:
      - image: Visual Studio 2017

  clone_folder: c:\gopath\src\github.com\midstar\webc

  environment:
    GOPATH: c:\gopath

  artifacts:
    - path: webc_windows_x64.zip
      name: webc_windows_x64.zip

# Special configurations for Linux
-
  matrix:
    only:
      - image: Ubuntu

  clone_folder: /usr/go/src/github.com/midstar/webc

  environment:
    GOPATH: /usr/go

  artifacts:
    - path: webc_linux_x64.tar.gz
      name: webc_linux_x64.tar.gz
    - path: webc_linux_arm.tar.gz
      name: webc_linux_arm.tar.gz

