name: webc builder 

on: [push, pull_request]

env:
  VERSION: 1.1.0.${{github.run_number}}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Check Environment
      run: |
        ls
        echo $NOW
        echo $VERSION
        echo $GITHUB_SHA

    - name: Build
      run: go build -v -ldflags="-X 'main.applicationBuildTime=$NOW -X main.applicationVersion=$VERSION -X main.applicationGitHash=$GITHUB_SHA" ./...

    - name: Test
      run: ./webc -v