name: webc builder 

on: [push, pull_request]

env:
  VERSION: 1.1.0.${{github.run_number}}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Check Environment
      run: |
        ls
        echo $DATETIME
        echo $VERSION
        echo $GITHUB_SHA

    - name: Build
      run: go build -v -ldflags="-X 'main.applicationBuildTime=$DATETIME' -X main.applicationVersion=$VERSION -X main.applicationGitHash=$GITHUB_SHA" ./...